Use hex rather than base64 for random string generation
So using a base64 string for the proxy secret actually causes the
hub container to fail to come up.

You would see errors like this in the hub pod:

```
[D 2021-03-26 10:08:57.600 JupyterHub proxy:766] Proxy: Fetching GET http://proxy-api:8001/api/routes
[W 2021-03-26 10:08:57.602 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:02.620 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:07.742 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:12.884 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:19.292 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:21.622 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:28.174 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[E 2021-03-26 10:09:28.174 JupyterHub app:2844]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2842, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2615, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 832, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 796, in api_request
        result = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 179, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Repeated api_request to proxy path "" failed.
```

In this commit we also remove the CryptKeeper configuration, as it
is not needed.

According to the docs https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html
there is a note that says:

As of version 1.0.0 this will automatically be generated and there is no need to set it manually.

Change-Id: I207376fa1917fde60ce4c957a2eb1491e2afc337